### ISSUE TITLE
Use JSON to detail data?

### ISSUE THREAD

**Issue by emoon** [emoon/68k_documentation_gen#1]
As suggested by @mattbettcher here https://docs.google.com/document/d/1ztZMiwmc8K0bMAI4FOQ0IzniEZdJgPg6SASTbRjdeuQ/edit

**Comment by mattbettcher** [comment]
To be honest it seems crazy verbose compared to just leaving it as code, but it does have all the info needed to gen the md.

**Comment by emoon** [comment]
yeah.. maybe it's better just have it as code really? Say that we have a config for 000/010/020/etc which is just code. Also the description would be the same in each file so maybe that can be general for shared instructions? Also with the latest changes the code is a bit more compact now also.

**Comment by mattbettcher** [comment]
I agree, I feel it would be easier to add the extra items directly in the source.

**Comment by emoon** [comment]
Lets do that!

**Comment by emoon** [comment]
I suggest something like this then

``` Rust
struct Description<'a> {
  operation: &'static str,
  assembler: &'a [&'static str],  
  attributes: &'static str,
}
```

Then in each instruction we add

``` Rust
struct Instruction<'a> {
  ...
  description: &'a Description,
}
```

That we we don't need to duplication the data for each table.
